# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/0ca677kdpr18w39ivjrwsb9kdjdx1xqp-hm-session-vars.fish/etc/profile.d/hm-session-vars.fish

# Source handler functions

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases

    # Interactive shell initialisation
    if test "$TERM" != dumb
        /nix/store/ilrxlvaydmr2qmsxqa07wiia3xrrdc1h-starship-1.24.2/bin/starship init fish | source

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/misaki/.local/share/fish/home-manager/generated_completions" $post
    end

    /nix/store/0k10ldsna7n046589r067579z9j5651k-direnv-2.37.1/bin/direnv hook fish | source

end
